### ISSUE TITLE
Set Environment Output and NodeJS version warnings in github actions

### ISSUE THREAD

**Issue by kvernon** [bhowell2/github-substring-action#3]
currently when running this actions, and thanks for making this tool. Google is currently will be deprecating some of the environments and save output strategies soon, and I was hoping this project could be updated.

Here are the warning below...

Environment output:

> Warning: The set-output command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Also, it references this project to need an update to node js:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: *************************************, bhowell2/github-substring-action

**Comment by groger** [comment]
+1

**Comment by bhowell2** [comment]
@kvernon thanks for this. Looking into it now.

**Comment by bhowell2** [comment]
@groger @kvernon this should be fixed now. Tested on a tmp repo. Still is v1/latest tag b/c API didnt change.
